export const systems = ["Xbox", "PC", "PS4"];

export const RECEIVE_COMMAND = 'RECEIVE_COMMAND';
export const RECEIVE_CONSOLE = 'RECEIVE_CONSOLE';

export const RECEIVE_API_REQUEST_METHODS = 'RECEIVE_API_REQUEST_METHODS';
export const RECEIVE_API_DATA = 'RECEIVE_API_DATA';

